# Generated by Django 4.2.3 on 2023-07-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("email", models.EmailField(max_length=100)),
                ("document", models.CharField(max_length=100, verbose_name="Document")),
                ("phone", models.CharField(max_length=100)),
                (
                    "registration_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
