# Generated by Django 4.2.3 on 2023-07-18 19:01

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(name="John", email="john@gmail.com", document="123456789", phone="123456789").save()


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
