# Generated by Django 4.2.3 on 2023-07-18 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="active",
        ),
        migrations.RemoveField(
            model_name="student",
            name="document",
        ),
        migrations.AddField(
            model_name="student",
            name="documents",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=20,
                verbose_name="Document",
            ),
            preserve_default=False,
        ),
    ]
