# Generated by Django 4.2.3 on 2023-07-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_remove_student_active_remove_student_document_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="documents",
            new_name="document",
        ),
    ]
